[minio]
Endpoint = "localhost:9000"
BucketName = "images"

[jwt]
Token = "peppa"
ExpiresIn = "1h"

[Redis]
DialTimeout = "10s"
ReadTimeout = "10s"

ServiceHost = "127.0.0.1"
ServicePort = 8081
Token = "secret_token"