basePath: /
host: 127.0.0.1
info:
  contact: {}
  description: Bmstu Open IT Platform
  license:
    name: AS IS (NO WARRANTY)
  title: BITOP
  version: "1.0"
paths: {}
schemes:
- https
- http
swagger: "2.0"
