basePath: /
definitions:
  app.SwaggerUpdateMissionRequest:
    properties:
      name:
        type: string
    type: object
  ds.Module:
    properties:
      description:
        type: string
      diameter:
        type: string
      image_url:
        type: string
      length:
        type: string
      mass:
        type: string
      name:
        type: string
      uuid:
        type: string
    required:
    - description
    - diameter
    - length
    - mass
    type: object
  schemes.AllMissionsResponse:
    properties:
      missions:
        items:
          $ref: '#/definitions/schemes.MissionOutput'
        type: array
    type: object
  schemes.AuthResp:
    properties:
      access_token:
        type: string
      token_type:
        type: string
    type: object
  schemes.GetAllModulesResponse:
    properties:
      draft_mission:
        type: string
      modules:
        items:
          $ref: '#/definitions/ds.Module'
        type: array
    type: object
  schemes.LoginReq:
    properties:
      login:
        maxLength: 30
        type: string
      password:
        maxLength: 30
        type: string
    required:
    - login
    - password
    type: object
  schemes.MissionOutput:
    properties:
      completion_date:
        type: string
      creation_date:
        type: string
      customer:
        type: string
      formation_date:
        type: string
      funding_status:
        type: string
      moderator:
        type: string
      name:
        type: string
      status:
        type: string
      uuid:
        type: string
    type: object
  schemes.MissionResponse:
    properties:
      mission:
        $ref: '#/definitions/schemes.MissionOutput'
      modules:
        items:
          $ref: '#/definitions/ds.Module'
        type: array
    type: object
  schemes.RegisterReq:
    properties:
      login:
        maxLength: 30
        type: string
      password:
        maxLength: 30
        type: string
    required:
    - login
    - password
    type: object
host: 127.0.0.1:80
info:
  contact: {}
  title: Lunar Gateway
  version: "1.0"
paths:
  /api/missions:
    delete:
      description: Удаляет черновую миссию
      responses:
        "200":
          description: OK
      summary: Удалить черновую миссию
      tags:
      - Миссии
    get:
      description: Возвращает все миссии с фильтрацией по статусу и дате формирования
      parameters:
      - description: статус перевозки
        in: query
        name: status
        type: string
      - description: начальная дата формирования
        in: query
        name: formation_date_start
        type: string
      - description: конечная дата формирвания
        in: query
        name: formation_completion_date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemes.AllMissionsResponse'
      summary: Получить все миссии
      tags:
      - Миссии
    put:
      description: Позволяет изменить название миссии и возвращает обновлённые данные
      parameters:
      - description: Название
        in: body
        name: name
        required: true
        schema:
          $ref: '#/definitions/app.SwaggerUpdateMissionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Указать название
      tags:
      - Миссии
  /api/missions/{id}:
    get:
      description: Возвращает подробную информацию о миссии
      parameters:
      - description: id миссии
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemes.MissionResponse'
      summary: Получить одну миссию
      tags:
      - Миссии
  /api/missions/{id}/moderator_confirm:
    put:
      description: Подтвердить или отменить миссию модератором
      parameters:
      - description: id миссии
        in: path
        name: id
        required: true
        type: string
      - description: подтвердить
        in: body
        name: confirm
        required: true
        schema:
          type: boolean
      responses:
        "200":
          description: OK
      summary: Подтвердить миссию
      tags:
      - Миссии
  /api/missions/delete_module/{id}:
    delete:
      description: Удалить модуль из черновой миссии
      parameters:
      - description: id модуля
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Удалить модуль из черновой миссии
      tags:
      - Миссии
  /api/missions/user_confirm:
    put:
      description: Сформировать миссию пользователем
      responses:
        "200":
          description: OK
      summary: Сформировать миссию
      tags:
      - Миссии
  /api/modules:
    get:
      description: Возвращает все доступные модули с опциональной фильтрацией по названию
      parameters:
      - description: название модуля для фильтрации
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemes.GetAllModulesResponse'
      summary: Получить все модули
      tags:
      - Модули
    post:
      consumes:
      - multipart/form-data
      description: Добавить новый модуль
      parameters:
      - description: Изображение модуля
        in: formData
        name: image
        type: file
      - description: Название
        in: formData
        name: name
        required: true
        type: string
      - description: Описание
        in: formData
        name: description
        required: true
        type: string
      - description: Масса
        in: formData
        name: mass
        required: true
        type: string
      - description: Длина
        in: formData
        name: length
        required: true
        type: integer
      - description: Диаметр
        in: formData
        name: diameter
        required: true
        type: integer
      responses:
        "200":
          description: OK
      summary: Добавить модуль
      tags:
      - Модули
  /api/modules/{id}:
    delete:
      description: Удаляет модуль по id
      parameters:
      - description: id модуля
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: Удалить модуль
      tags:
      - Модули
    get:
      description: Возвращает более подробную информацию об одном модуле
      parameters:
      - description: id модуля
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ds.Module'
      summary: Получить один модуль
      tags:
      - Модули
    put:
      consumes:
      - multipart/form-data
      description: Изменить данные полей о модуле
      parameters:
      - description: Идентификатор модуля
        in: path
        name: id
        required: true
        type: string
      - description: Изображение модуля
        in: formData
        name: image
        type: file
      - description: Название
        in: formData
        name: name
        required: true
        type: string
      - description: Описание
        in: formData
        name: description
        required: true
        type: string
      - description: Масса
        in: formData
        name: mass
        required: true
        type: string
      - description: Длина
        in: formData
        name: length
        required: true
        type: integer
      - description: Диаметр
        in: formData
        name: diameter
        required: true
        type: integer
      responses:
        "200":
          description: OK
      summary: Изменить модуль
      tags:
      - Модули
  /api/modules/{id}/add_to_mission:
    post:
      description: Добавить выбранный модуль в черновик миссии
      parameters:
      - description: id модуля
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: Добавить в миссию
      tags:
      - Модули
  /api/user/login:
    post:
      consumes:
      - application/json
      description: Авторизует пользователя по логиню, паролю и отдаёт jwt токен для
        дальнейших запросов
      parameters:
      - description: login and password
        in: body
        name: user_credentials
        required: true
        schema:
          $ref: '#/definitions/schemes.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemes.AuthResp'
      summary: Авторизация
      tags:
      - Авторизация
  /api/user/logout:
    get:
      consumes:
      - application/json
      description: Выход из аккаунта
      responses:
        "200":
          description: OK
      summary: Выйти из аккаунта
      tags:
      - Авторизация
  /api/user/sign_up:
    post:
      consumes:
      - application/json
      description: Регистрация нового пользователя
      parameters:
      - description: login and password
        in: body
        name: user_credentials
        required: true
        schema:
          $ref: '#/definitions/schemes.RegisterReq'
      responses:
        "200":
          description: OK
      summary: Регистрация
      tags:
      - Авторизация
schemes:
- http
swagger: "2.0"
